### ISSUE TITLE
why not working

### ISSUE THREAD

**Issue by liyuan1125** [wobsoriano/vue-driver#1]
```vue
<script setup lang="ts">
  import { useDriver } from 'vue3-driver'

  const driver = useDriver()

 onMounted(() => {
    driver.setConfig({
      showProgress: true,
      steps: [
        {
          element: '#test1',
          popover: { title: 'test1', description: 'test1' },
        },
        {
          element: '#test2',
          popover: { title: 'test2', description: 'test2' },
        },
      ],
    })

 driver.drive()
  })
</script>
```

**Comment by hamonCordova** [comment]
Is there a solution?

**Comment by wobsoriano** [comment]
Did y’all install the plugin?

**Comment by hamonCordova** [comment]
Yeah. When using the directives it works, but in the case of the initial code shared here it doesn't work and did't trow any error.
The only solution that i get was using the driver.js directly.

Example: 



    import { driver } from "driver.js";
    
    const driverObj = driver({
        showProgress: true,
        steps: [
          { element: '#test', popover: { title: 'Title', description: 'Description' } },
        ]
    });
    
    driverObj.drive();

**Comment by wobsoriano** [comment]
Ah yes, I think there’s no reason to use this library if you plan on using IDs and adding the selectors manually. That’s the main purpose of the directives here - to bind the elements without referencing them via `steps` property.

If you still want to use selectors, you can add the initial config to the plugin:

```ts
app.use(VueDriver, {
  showProgress: true,
  mergeSteps: true, // This merges your directives and steps declared in this config
  steps: [
    {
      element: '#test1',
      popover: { title: 'test1', description: 'test1' },
    },
    {
      element: '#test2',
      popover: { title: 'test2', description: 'test2' },
    },
  ],
})
```
